version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-*'
      dev-tools:
        dependency-type: development
    open-pull-requests-limit: 10

  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
